- hosts: awsmn
  tasks:
    - name: Download docker.repo at yum.repos.d
      get_url:
          url: "https://download.docker.com/linux/rhel/docker-ce.repo"
          dest: /etc/yum.repos.d

    - name: updateing my bug in docker repo file
      replace:
             path: /etc/yum.repos.d/docker-ce.repo
             regexp: "rhel"
             replace: "centos"

    - name: installing docker 
      package:
           name: "docker-ce"
           state: present
          

    - name: starting service
      service:
             name: "docker" 
             state: started
             enabled: yes
                 
